/**
 * Finite permutation-group algebra for the monodromy explorer (C3). From the generator permutations `σᵢ`
 * (each the monodromy of a lasso loop around a branch point, all expressed over one common base-point sheet
 * labeling — see `generatorLoop.ts`), derive the **monodromy group** `⟨σᵢ⟩ ≤ Sₙ`, whether it acts
 * **transitively** (⇔ the surface is connected), and — with the ramification cycle types — the **genus** via
 * Riemann–Hurwitz. Pure; unit-tested.
 *
 * Honesty: the group and the genus are `≈` (built from the never-certified permutations, RISKS §3); the
 * Riemann–Hurwitz **formula** and its **parity/bound consistency check** are exact combinatorics — a genuine
 * self-check that flags mis-estimated permutations (a valid degree-`n` cover of the sphere must give an even
 * total ramification and a non-negative integer genus).
 */
/** A permutation of `{0, …, n−1}`: `perm[i]` is the image of `i`. */
export type Perm = number[];

export function identityPerm(n: number): Perm {
  return Array.from({ length: n }, (_, i) => i);
}

/** `(a ∘ b)(i) = a[b[i]]` — apply `b`, then `a`. (The generated group is independent of this convention.) */
export function compose(a: Perm, b: Perm): Perm {
  return b.map((bi) => a[bi]);
}

export function inverse(a: Perm): Perm {
  const inv = new Array<number>(a.length);
  for (let i = 0; i < a.length; i++) inv[a[i]] = i;
  return inv;
}

export function isIdentity(p: Perm): boolean {
  return p.every((pi, i) => pi === i);
}

/** Cycle decomposition **including fixed points** as singleton cycles (0-based indices). */
export function cycles(p: Perm): number[][] {
  const seen = new Array<boolean>(p.length).fill(false);
  const out: number[][] = [];
  for (let i = 0; i < p.length; i++) {
    if (seen[i]) continue;
    const cyc: number[] = [];
    let j = i;
    while (!seen[j]) {
      seen[j] = true;
      cyc.push(j);
      j = p[j];
    }
    out.push(cyc);
  }
  return out;
}

/** The number of orbits (cycles, counting fixed points) of `p`. */
export function cycleCount(p: Perm): number {
  return cycles(p).length;
}

export interface GroupInfo {
  /** The order of `⟨gens⟩` (or the cap, if reached). */
  order: number;
  /** True when the BFS hit `cap` before closing — `order` is then a lower bound ("≥ cap"). */
  capped: boolean;
  /** True when `⟨gens⟩` acts transitively on `{0,…,n−1}` ⇔ the cover (Riemann surface) is connected. */
  transitive: boolean;
}

/**
 * The subgroup `⟨gens⟩ ≤ Sₙ` generated by `gens`, by breadth-first closure under composition, **capped** at
 * `cap` elements so a high-degree cover can't hang the UI (past the cap, `order` is a lower bound). Transitive
 * is computed directly from the generators' orbit of `0`, independent of the cap.
 */
export function generatedGroup(gens: Perm[], n: number, cap = 100_000): GroupInfo {
  const key = (p: Perm): string => p.join(",");
  const id = identityPerm(n);
  const seen = new Set<string>([key(id)]);
  const frontier: Perm[] = [id];
  let capped = false;
  while (frontier.length) {
    const p = frontier.pop() as Perm;
    for (const g of gens) {
      const q = compose(g, p);
      const k = key(q);
      if (!seen.has(k)) {
        if (seen.size >= cap) {
          capped = true;
          break;
        }
        seen.add(k);
        frontier.push(q);
      }
    }
    if (capped) break;
  }
  return { order: seen.size, capped, transitive: isTransitive(gens, n) };
}

/** Whether `gens` act transitively on `{0,…,n−1}` — the orbit of `0` is everything (⇔ connected surface). */
export function isTransitive(gens: Perm[], n: number): boolean {
  if (n <= 1) return true;
  const reached = new Set<number>([0]);
  const stack = [0];
  while (stack.length) {
    const i = stack.pop() as number;
    for (const g of gens) {
      const j = g[i];
      if (!reached.has(j)) {
        reached.add(j);
        stack.push(j);
      }
      const jb = g.indexOf(i); // also follow g⁻¹ so the orbit is under the generated group
      if (jb >= 0 && !reached.has(jb)) {
        reached.add(jb);
        stack.push(jb);
      }
    }
  }
  return reached.size === n;
}

export interface GenusResult {
  /** The genus `g` of the Riemann surface (a cover of the sphere), or null when the data is inconsistent. */
  genus: number | null;
  /** Total ramification `R = Σ (n − #cycles(σ))` over all branch points including ∞. */
  ramification: number;
  /** True when `R` is even and `g ≥ 0` — a necessary condition for a genuine degree-`n` cover of the sphere. */
  consistent: boolean;
}

/**
 * The genus via **Riemann–Hurwitz** for a degree-`n` branched cover of the sphere: `2 − 2g = 2n − R`, where
 * `R = Σ (n − #cycles(σ))` summed over every branch point's local monodromy `σ` **including ∞**. Pass the
 * `cycleCounts` = the number of cycles of each such `σ` (finite branch points *and* `∞`). Returns `genus = null`
 * with `consistent = false` when `R` is odd or `g < 0` — the estimates then can't come from a real cover, a
 * built-in self-check.
 */
export function riemannHurwitzGenus(cycleCounts: readonly number[], n: number): GenusResult {
  let R = 0;
  for (const c of cycleCounts) R += n - c;
  const twoG = R - 2 * n + 2; // = 2g
  const consistent = R % 2 === 0 && twoG >= 0;
  return { genus: consistent ? twoG / 2 : null, ramification: R, consistent };
}

/**
 * A recognizable name for a small monodromy group given its order, sheet count, and transitivity — enough to
 * label the common cases without a group-classification engine. Returns null when nothing obvious fits.
 */
export function namedGroup(order: number, n: number, transitive: boolean): string | null {
  if (order === 1) return "trivial";
  if (order === n && transitive) return `C${n} (cyclic)`;
  if (order === factorial(n)) return `S${n} (symmetric)`;
  if (order === factorial(n) / 2 && n >= 3) return `A${n} (alternating)`;
  if (order === 2 * n && n >= 3) return `D${n} (dihedral)`;
  return null;
}

function factorial(n: number): number {
  let f = 1;
  for (let i = 2; i <= n; i++) f *= i;
  return f;
}
