// The Faber-polynomial side of potential theory (M3.2). The Faber polynomials Fₙ of a compact set K are
// generated by K's exterior map Ψ (Fₙ(Ψ(w)) = wⁿ + O(1/w)); their ZEROS realize the equilibrium measure
// as a limit — the zero-counting measure ν(Fₙ) →* μ_K — and their GROWTH realizes the Green's function,
// (1/n)log|Fₙ| → g_K + log cap. This module adapts an ExteriorDomain (potentialDomain.ts) to @cas/faber's
// ExteriorMap and hands back the zeros of F₁…F_N via @cas/faber's `faberConvergence` (which builds the
// polynomials by the Faber recurrence and root-finds each order, honestly flagging non-convergence at
// high degree, where the monomial basis is ill-conditioned).
//
// HONESTY: ν(Fₙ) →* μ_K only when ∂K is not too smooth. It holds for corners (segment → the Chebyshev /
// arcsine nodes; polygons → ∂K), but for a SMOOTH boundary the zeros stay interior — a disk collapses
// them to the centre, an ellipse to its focal segment. The view labels this rather than overclaiming.
import { faberConvergence, type ExteriorMap } from "@cas/faber";
import type { Cx } from "@cas/core";
import type { Pt } from "./transplant.js";
import type { ExteriorDomain } from "./potentialDomain.js";

/** An ExteriorDomain's exterior map as the @cas/faber contract (Ψ(z) = c·z + Σ cₖ z⁻ᵏ, laurent[k] = cₖ). */
export function toExteriorMap(domain: ExteriorDomain): ExteriorMap {
  return { c: domain.capacity, laurent: domain.laurent.map((z): Cx => ({ re: z[0], im: z[1] })) };
}

/** The zeros of one Faber order. */
export interface FaberOrder {
  readonly n: number;
  readonly zeros: Pt[];
  readonly converged: boolean;
  readonly residual: number;
}

/**
 * The zeros of the Faber polynomials F₁…F_N of K, per order. Reads the domain's Laurent map and defers to
 * @cas/faber's `faberConvergence` (Faber recurrence + Durand–Kerner root-finding, Newton-polished). Each
 * order carries an honest `converged`/`residual` — a high-degree order can fail (monomial-basis
 * conditioning), which the caller surfaces as `≈`/⚠ rather than drawing bogus roots.
 */
export function faberZerosUpTo(domain: ExteriorDomain, N: number): FaberOrder[] {
  return faberConvergence(toExteriorMap(domain), Math.max(1, Math.floor(N))).map((e) => ({
    n: e.n,
    zeros: e.roots.map((r): Pt => [r.re, r.im]),
    converged: e.converged,
    residual: e.residual,
  }));
}

/** The zeros of a single Faber order n (convenience over {@link faberZerosUpTo}). */
export function faberZeros(domain: ExteriorDomain, n: number): FaberOrder {
  const orders = faberZerosUpTo(domain, n);
  return orders[orders.length - 1];
}
