import { describe, expect, it } from "vitest";
import {
  compose,
  cycles,
  groupElements,
  inverse,
  isPrimitive,
  isTransitive,
  sign,
  type Perm,
} from "@cas/monodromy";
import {
  alternatingGroup,
  groupByLabel,
  groupsOfDegree,
  standardGroup,
  symmetricGroup,
  typeKey,
} from "../src/engine/galois/tables.js";
import { registerTable } from "../src/engine/galois/tables.js";
import large from "../src/engine/galois/data/transitive-8-15.json";

registerTable(large);

// The table is generated by GAP; everything here re-derives it with the app's own permutation code,
// so the data and the engine that reads it cannot disagree about a convention unnoticed.

const A002106 = [0, 0, 1, 2, 5, 5, 16, 7, 50, 34, 45, 8, 301, 9, 63, 104];

const key = (p: Perm): string => p.join(",");
function elementSet(gens: readonly Perm[], n: number): Set<string> {
  const { elements, capped } = groupElements([...gens], n, 10_000);
  if (capped) throw new Error("too large to list");
  return new Set(elements.map(key));
}
const typeOf = (p: Perm): string => typeKey(cycles(p).map((c) => c.length));

describe("the transitive-group table", () => {
  it("holds every transitive group of degree 2–15 (OEIS A002106)", () => {
    for (let n = 2; n <= 15; n++)
      expect(groupsOfDegree(n).length, `degree ${n}`).toBe(A002106[n]);
  });

  it("degree ≤ 7: the order, the cycle types, parity, primitivity and transitivity re-derive exactly", () => {
    for (let n = 2; n <= 7; n++)
      for (const g of groupsOfDegree(n)) {
        const { elements } = groupElements([...g.generators], n, 10_000);
        expect(elements.length, g.label).toBe(g.order);
        const counts: Record<string, number> = {};
        for (const e of elements) counts[typeOf(e)] = (counts[typeOf(e)] ?? 0) + 1;
        expect(counts, g.label).toEqual(g.cycleTypes);
        expect(
          elements.every((e) => sign(e) === 1),
          g.label,
        ).toBe(g.even);
        expect(isTransitive([...g.generators], n), g.label).toBe(true);
        expect(isPrimitive(g.generators, n), g.label).toBe(g.primitive);
      }
  });

  it("degree ≤ 7: each maximal class is a transitive subgroup, conjugate by its π to the group it names", () => {
    let classes = 0;
    for (let n = 2; n <= 7; n++)
      for (const g of groupsOfDegree(n)) {
        const G = elementSet(g.generators, n);
        for (const m of g.maximalTransitive ?? []) {
          classes++;
          const K = elementSet(m.generators, n);
          for (const k of K) expect(G.has(k), `${m.label} in ${g.label}`).toBe(true);
          const H = groupByLabel(m.label);
          expect(K.size).toBe(H.order);
          expect(H.order < g.order).toBe(true);
          const conj = new Set(
            [...elementSet(H.generators, n)].map((h) =>
              key(compose(m.conj, compose(h.split(",").map(Number), inverse(m.conj)))),
            ),
          );
          expect(conj, `${m.label} in ${g.label}`).toEqual(K);
        }
      }
    // Anti-vacuity, and the one class-splitting case: A₇ holds TWO classes of PSL(3,2).
    expect(classes).toBeGreaterThan(40);
    expect(groupByLabel("7T6").maximalTransitive?.map((m) => m.label)).toEqual([
      "7T5",
      "7T5",
    ]);
  });

  it("degree 8–15: every group is transitive, and the small ones have the stated order and types", () => {
    for (let n = 8; n <= 15; n++)
      for (const g of groupsOfDegree(n)) {
        expect(isTransitive([...g.generators], n), g.label).toBe(true);
        const total = Object.values(g.cycleTypes).reduce((a, b) => a + b, 0);
        expect(total, g.label).toBe(g.order);
        if (g.order <= 2000) {
          const { elements } = groupElements([...g.generators], n, 10_000);
          expect(elements.length, g.label).toBe(g.order);
        }
      }
  });

  it("names Sₙ and Aₙ, and pairs 8T10 with 8T11 as statistically indistinguishable", () => {
    expect(symmetricGroup(5).label).toBe("5T5");
    expect(alternatingGroup(5)?.label).toBe("5T4");
    expect(alternatingGroup(2)).toBeNull();
    expect(symmetricGroup(15).order).toBe(1307674368000);
    expect(groupByLabel("8T10").sameStatisticsAs).toEqual(["8T11"]);
    expect(groupByLabel("8T11").sameStatisticsAs).toEqual(["8T10"]);
    for (let n = 2; n <= 15; n++)
      for (const g of groupsOfDegree(n))
        for (const o of g.sameStatisticsAs)
          expect(groupByLabel(o).sameStatisticsAs, `${g.label} ~ ${o}`).toContain(
            g.label,
          );
    expect(groupByLabel("7T5").name).toBe("PSL(3,2)");
    expect(groupByLabel("7T5").solvable).toBe(false);
  });
});

describe("Sₙ and Aₙ without the table (the main thread before degrees 8–15 arrive)", () => {
  it("carry the table's own label, order and parity, and generate a group of that order and parity", () => {
    for (let n = 3; n <= 15; n++)
      for (const alt of [false, true]) {
        const s = standardGroup(n, alt);
        const t = alt ? alternatingGroup(n) : symmetricGroup(n);
        expect(s.label, `${n} ${alt}`).toBe(t?.label);
        expect(s.order).toBe(t?.order);
        expect(s.even).toBe(t?.even);
        if (alt)
          expect(
            s.generators.every((g) => sign(g) === 1),
            `A${n}`,
          ).toBe(true);
        if (n <= 7)
          expect(
            groupElements([...s.generators], n, 10_000).elements.length,
            `${n} ${alt}`,
          ).toBe(s.order);
        expect(isTransitive([...s.generators], n)).toBe(true);
      }
  });
});
