// The ideal triangle reflection group Γ = ℤ/2 ∗ ℤ/2 ∗ ℤ/2 — the "group side" of the deltoid mating
// (Lee–Lyubich–Makarov–Mukherjee, arXiv:1811.04979). Γ is generated by reflections in the three sides of
// an ideal triangle in the Poincaré disk 𝔻, with ideal vertices at the cube roots of unity {1, ω, ω²}.
//
// A geodesic side joining two ideal vertices 120° apart is the circular arc orthogonal to ∂𝔻; that
// orthogonal circle has centre 2·(bisector direction) and radius √3 (orthogonality: |C|² = 1 + 3 = 4 ✓).
// Reflection in that circle is the inversion R_k(z) = C_k + 3·(z − C_k)/|z − C_k|² (anti-conformal).
//
// This module is the model dynamics; the mating glue (mating/glue.ts) pushes its tessellation through
// φ∘η onto the deltoid σ-plane, where it must coincide with the σ tiling we already render — the
// correctness anchor for the whole mating visualizer.
import type { Complex } from "../deltoid.js";

/** The three ideal vertices: cube roots of unity on ∂𝔻. */
export const IDEAL_VERTICES: readonly Complex[] = [
  [1, 0],
  [-0.5, Math.sqrt(3) / 2],
  [-0.5, -Math.sqrt(3) / 2],
];

export interface ReflectionCircle {
  center: Complex;
  /** Radius². (radius = √3.) */
  r2: number;
}

// Side k is the geodesic between vertices k and (k+1) mod 3; its orthogonal circle is centred at
// 2·e^{i·(bisector angle)} with radius √3. Bisector angles: 60°, 180°, 300°.
export const REFLECTION_CIRCLES: readonly ReflectionCircle[] = [0, 1, 2].map((k) => {
  const bisector = (Math.PI / 3) * (2 * k + 1); // 60°, 180°, 300°
  return { center: [2 * Math.cos(bisector), 2 * Math.sin(bisector)] as Complex, r2: 3 };
});

/** Reflection (circle inversion) R_k: z ↦ C_k + r²·(z − C_k)/|z − C_k|². Anti-conformal involution. */
export function reflect(k: number, z: Complex): Complex {
  const c = REFLECTION_CIRCLES[k].center;
  const dx = z[0] - c[0];
  const dy = z[1] - c[1];
  const d2 = dx * dx + dy * dy;
  if (d2 < 1e-300) return [Infinity, Infinity]; // the circle's centre maps to ∞
  const s = REFLECTION_CIRCLES[k].r2 / d2;
  return [c[0] + s * dx, c[1] + s * dy];
}

/** True when z is in the fundamental ideal triangle: inside 𝔻 and outside all three reflection circles. */
export function inFundamental(z: Complex): boolean {
  if (z[0] * z[0] + z[1] * z[1] >= 1) return false;
  for (const circle of REFLECTION_CIRCLES) {
    const dx = z[0] - circle.center[0];
    const dy = z[1] - circle.center[1];
    if (dx * dx + dy * dy <= circle.r2) return false; // inside a reflection circle → not fundamental
  }
  return true;
}

export interface Tile {
  /** The reduced group word (letters 0..2) taking the fundamental tile to this one. [] = fundamental. */
  word: number[];
  depth: number;
  /** g applied to z (g = R_{word[0]} ∘ … ∘ R_{word[n-1]}). */
  apply: (z: Complex) => Complex;
  /** A representative interior point, g(0) — 0 lies in the fundamental tile. */
  rep: Complex;
}

/**
 * Tessellate 𝔻 by BFS over reduced words in Γ (no letter repeats, since R_k² = id), to `maxDepth`.
 * A tile at word g has neighbours g∘R_k across its edges; g(0) is a representative interior point.
 * Tile counts: depth 0 → 1, depth d≥1 → 3·2^{d−1} new (total 3·2^d − 2).
 */
export function tessellate(maxDepth: number): Tile[] {
  const id = (z: Complex): Complex => z;
  const root: Tile = { word: [], depth: 0, apply: id, rep: [0, 0] };
  const tiles: Tile[] = [root];
  const queue: Tile[] = [root];
  let head = 0;
  while (head < queue.length) {
    const g = queue[head++];
    if (g.depth >= maxDepth) continue;
    const last = g.word.length > 0 ? g.word[g.word.length - 1] : -1;
    for (let k = 0; k < 3; k++) {
      if (k === last) continue; // reduced word: R_k∘R_k = id
      const parentApply = g.apply;
      const apply = (z: Complex): Complex => parentApply(reflect(k, z));
      const tile: Tile = { word: [...g.word, k], depth: g.depth + 1, apply, rep: apply([0, 0]) };
      tiles.push(tile);
      queue.push(tile);
    }
  }
  return tiles;
}

/** Sample the fundamental tile's three edges as polylines (each an arc of a reflection circle inside 𝔻).
 *  Apply a tile's `apply` to these to draw that tile's edges. */
export function fundamentalEdges(samples = 24): Complex[][] {
  return [0, 1, 2].map((k) => {
    const c = REFLECTION_CIRCLES[k].center;
    const r = Math.sqrt(REFLECTION_CIRCLES[k].r2);
    // The edge is the arc of circle k between the two vertices it joins (k and k+1), taken inside 𝔻.
    const va = IDEAL_VERTICES[k];
    const vb = IDEAL_VERTICES[(k + 1) % 3];
    const a0 = Math.atan2(va[1] - c[1], va[0] - c[0]);
    let a1 = Math.atan2(vb[1] - c[1], vb[0] - c[0]);
    // Take the short arc (the one bowing through 𝔻).
    let d = a1 - a0;
    while (d > Math.PI) d -= 2 * Math.PI;
    while (d < -Math.PI) d += 2 * Math.PI;
    a1 = a0 + d;
    const pts: Complex[] = [];
    for (let i = 0; i <= samples; i++) {
      const a = a0 + (d * i) / samples;
      pts.push([c[0] + r * Math.cos(a), c[1] + r * Math.sin(a)]);
    }
    return pts;
  });
}

/**
 * The Nielsen map N: 𝔻 → 𝔻 — the degree-2 expanding "reflection map" that the mating conjugates σ to.
 * On the region inside reflection circle k, N = R_k; on the fundamental tile it is undefined (returns
 * null). (Kept for the map-side/dynamics milestones; the correctness spike uses only the tessellation.)
 */
export function nielsen(z: Complex): Complex | null {
  for (let k = 0; k < 3; k++) {
    const c = REFLECTION_CIRCLES[k].center;
    const dx = z[0] - c[0];
    const dy = z[1] - c[1];
    if (dx * dx + dy * dy < REFLECTION_CIRCLES[k].r2) return reflect(k, z);
  }
  return null; // in the fundamental tile — no reflection to apply
}
